default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV["DB_POOL"] || 5  %>
  database: <%= ENV['DB_NAME'] || 'seshat-jets-2_development' %>
  encoding: utf8mb4
  username: <%= ENV['DB_USER'] || 'root' %>
  password: <%= ENV['DB_PASS'] %>
  host: <%= ENV["DB_HOST"] %>
  url: <%= ENV['DATABASE_URL'] %> # takes higher precedence than other settings

development:
  <<: *default
  database: <%= ENV['DB_NAME'] || 'seshat-jets-2_development' %>

test:
  <<: *default
  database: seshat-jets-2_test

production:
  <<: *default
  database: seshat-jets-2_production
  url: <%= ENV['DATABASE_URL'] %>
